---
- hosts: jenkins
  vars_files:
      - vars/main.yml
  vars:
    spf13_output_file_name: spf13-script.sh
    apt_install_packages: 
        - git 
        - python
        - python-pip
        - lsb
        - ansible 
        - vim
        - zsh
        - build-essential
        - sudo
        - docker

    user_name: "{{ ansible_user_id }}"

  gather_facts: False
  pre_tasks:
     - name: Install python2 
       raw: test -e /usr/bin/python || (apt -y update && apt install -y python python-pip)
       changed_when: False
       become: true
       become_method: sudo

     - setup: # aka gather_facts

     - name: upgrade packages
       apt: 
            update_cache: yes
            cache_valid_time: 3600
            name: "{{ apt_install_packages }}"
       become: true
       become_method: sudo

  roles:
      - role: gantsign.oh-my-zsh
        users:
            - username: "{{ user_name }}"
              oh_my_zsh:
                  theme: agnoster
                  plugins:
                      - git
                      - git-extras
                      - colorize
                      - colored-man-pages
                      - ubuntu
                      - wd
                      - gnu-utils
                      - nmap
                      - npm
                      - nvm
                      - python
                      - rsync
                      - systemadmin
                      - common-aliases
                      - zsh-syntax-highlighting

      - role: mjanser.powerline
        powerline_users:
            - "{{ user_name }}"
        become: true
        become_method: sudo

      - role: manala.ansible-galaxy
        manala_ansible_galaxy_roles:
            - geerlingguy.java
            - manala.ansible-galaxy
        become: true
        become_method: sudo

      - role: geerlingguy.jenkins
        become: true
        become_method: sudo

      - role: geerlingguy.firewall
        become: true
        become_method: sudo

      - role: geerlingguy.ntp
        become: true
        become_method: sudo

      - role: geerlingguy.git
        become: true
        become_method: sudo

      - role: geerlingguy.java
        become: true
        become_method: sudo

      - role: geerlingguy.jenkins
        become: true
        become_method: sudo

      #- role: vozerov.sudo
        #sudo_sudoers:
            #- name: %sudo
            #- nopasswd: true
        #sudo_sudoers_d:
            #- name: jenkins


