---
- hosts: all
  vars:
    spf13_output_file_name: spf13-script.sh
    apt_install_packages: git
    user_name: "{{ ansible_user_id }}"

  pre_tasks:
     - name: upgrade packages
       apt: 
            update_cache: yes
            cache_valid_time: 3600
       become: true
       become_method: sudo


  roles:
      - role: gantsign.oh-my-zsh
        users:
            - username: "{{ user_name }}"
              oh_my_zsh:
                  theme: agnoster
                  plugins:
                      - git
                      - git-extras
                      - colorize
                      - colored-man-pages
                      - ubuntu
                      - wd
                      - gnu-utils
                      - nmap
                      - npm
                      - nvm
                      - python
                      - rsync
                      - systemadmin
                      - common-aliases
                      - zsh-syntax-highlighting

      - role: mjanser.powerline
        powerline_users:
            - "{{ user_name }}"
        become: true
        become_method: sudo

      - role: angstwad.docker_ubuntu
        docker_group_members: "{{ user_name }}"
        become: true
        become_method: sudo

      - role: bareflank_basics

