---
- name: add cmake repo
  apt_repository: repo='ppa:george-edison55/cmake-3.x' state=present
  become: true
  become_method: sudo

- name: add ubuntu testing repos
  apt_repository: repo='ppa:ubuntu-toolchain-r/test' state=present
  become: true
  become_method: sudo

- name: update apt cache
  apt: update_cache=yes
  become: true
  become_method: sudo

- name: install bareflank deps
  apt: name={{ build_packages }} state=present
  become: true
  become_method: sudo


- name: install usability packages
  apt: name={{ dev_packages }} state=present
  become: true
  become_method: sudo

- name: Dist-upgrade
  apt:
      update_cache: yes
      upgrade: dist
      cache_valid_time: 3600
  become: true
  become_method: sudo

- name: clone zsh syntax highlighting
  git: repo=http://github.com/zsh-users/zsh-syntax-highlighting.git 
          dest=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
          update=yes
  become: true
  become_user: "{{ ansible_user_id }}"
  become_method: sudo


#- name: Download spf13 vim install script
  #get_url: url=http://j.mp/spf13-vim3 dest=~/{{ spf13_output_file_name }}
  #run_once: true
  #become: true
  #become_user: "{{ user_name }}"

#- name: launch spf13 install script
  #command: sh ~/{{ spf13_output_file_name }}
  #run_once: true
  #become: true
  #become_user: "{{ user_name }}"


- name: patch printf.h
  replace: dest=/usr/include/printf.h regexp='__wur __THROW' replace='__THROW __wur' backup=yes
  become: true
  become_method: sudo

- name: test env
  shell: echo "WORKSPACE = ${WORKSPACE}"
  register: my_jenkins_workspace

- debug: msg="WORKSPACE={{ lookup('env', 'WORKSPACE') }}"
- debug: msg="WORKSPACE={{ my_jenkins_workspace }}"
- debug: msg="WORKSPACE={{ ansible_env.WORKSPACE | mandatory  }}"

- name: Clone Hypervisor Super Project
  git: repo=git@github.com:/ilovepi/hypervisor-super.git
          dest={{ project_root }}
          version=no-submodules
          depth=1
          accept_hostkey=true
          update=yes
  become: true
  become_user: "{{ user_name }}"

- name: Clone Hypervisor Super project
  git: repo=git@github.com:/ilovepi/hypervisor.git
          dest={{ project_root }}/hypervisor
          version=master
          depth=1
          accept_hostkey=true
          update=yes
  become: true
  become_user: "{{ user_name }}"

- name: clone multicompiler super project
  git: repo=git@github.com:/ilovepi/multicompiler-automation.git
          dest={{ project_root }}/multicompiler
          version=no-submodules
          depth=1
          accept_hostkey=true
          update=yes
  become: true
  become_user: "{{ user_name }}"

- name: clone multi compiler project
  git: repo=git@github.com:/securesystemslab/multicompiler-priv.git
          dest={{ project_root }}/multicompiler/llvm
          version=cfar_38
          update=yes
          depth=1
          accept_hostkey=true
  become: true
  become_user: "{{ user_name }}"

- name: Clone Multi Compiler Clang
  git: repo=git@github.com:/securesystemslab/multicompiler-clang-priv.git
          dest={{ project_root }}/multicompiler/llvm/tools/clang
          version=cfar_38
          update=yes
          depth=1
          accept_hostkey=true
  become: true
  become_user: "{{ user_name }}"

- name: Clone Multi Compiler Compiler-RT
  git: repo=git@github.com:/securesystemslab/multicompiler-compiler-rt-priv.git
          dest={{ project_root }}/multicompiler/llvm/projects/compiler-rt
          version=cfar_38
          update=yes
          depth=1
          accept_hostkey=true
  become: true
  become_user: "{{ user_name }}"

- name: Clone Multi Compiler PoolAlloc
  git: repo=git@github.com:/securesystemslab/poolalloc
          dest={{ project_root }}/multicompiler/llvm/projects/poolalloc
          version=cfar_38
          update=yes
          depth=1
          accept_hostkey=true
  become: true
  become_user: "{{ user_name }}"

- name: Clone Multi Compiler SVF
  git: repo=git@github.com:/rboggild/SVF
          dest={{ project_root }}/multicompiler/llvm/projects/svf
          depth=1
          update=yes
          accept_hostkey=true
  become: true
  become_user: "{{ user_name }}"

- name: Clone Gold Linker
  git: repo=git@github.com:/securesystemslab/binutils.git
          dest={{ project_root }}/multicompiler/binutils
          depth=1
          update=yes
          version=random_commons-2_26
          accept_hostkey=true
  become: true
  become_user: "{{ user_name }}"
